[stations]
selected_profile = "1_ACC"

[stations.profiles.4_REGIONALS]
include = [
    "EK*",
    "*_FMP",
]
exclude = ["EKCH*"]
priority = [
    "DK_FMP",
    "*_FMP",
    "APP CO",
    "DK*",
    "APP*",
    "DEP*",
    "CH*",
    "BI*",
    "YT*",
    "AH*",
    "KA*",
    "SP*",
    "RN*",
    "VJ*",
    "SB*",
    "OD*",
    "EB*",
]
frequencies = "ShowAll"
grouping = "None"

[stations.profiles.4_REGIONALS.aliases]
"123.730" = "DK E"
"134.680" = "DK N"
"118.305" = "YT TWR"
"119.580" = "KA TWR"
"120.430" = "KA APP"
"128.215" = "DK C"
"135.565" = "DK V"
"121.380" = "DK I"
"119.280" = "AH APP"
"126.400" = "SB AFIS"
"118.280" = "SP TWR"
"136.485" = "DK UA"
"133.155" = "DK D"
"119.055" = "BI TWR"
"135.290" = "DK A"
"119.555" = "DK B"
"127.865" = "DK UC"
"136.555" = "DK UN"
"121.405" = "VJ AFIS"
"123.980" = "YT APP"
"118.530" = "AH TWR"
"127.580" = "BI APP"
"124.555" = "DK L"
"124.105" = "SP APP"
"125.530" = "RK APP"
"120.705" = "YT FIN"
"119.530" = "OD AFIS"
"126.055" = "DK UV"
"131.040" = "DK FMP"
"120.155" = "EB AFIS"
"119.255" = "BI FIN"

[stations.profiles.1_ACC]
include = [
    "EK*",
    "EDDH*_APP",
    "EDUU*H*CTR",
    "EDUU*O*CTR",
    "EDUU*OH*CTR",
    "EDWW*A*CTR",
    "EDWW*B*CTR",
    "EDWW*E*CTR",
    "EDWW*H*CTR",
    "EDWW*K*CTR",
    "EDWW*M*CTR",
    "EDWW*W*CTR",
    "EDWW_CTR",
    "EDYY*BB*CTR",
    "EDYY*HH*CTR",
    "EDYY*HL*CTR",
    "EDYY*JH*CTR",
    "EDYY*JL*CTR",
    "ENOR*S*CTR",
    "ENOR_CTR",
    "ENOS*4*CTR",
    "ENOS*8*CTR",
    "ENOS_CTR",
    "ENSV*N*CTR",
    "ENSV*O*CTR",
    "ENSV*W*CTR",
    "ENSV_CTR",
    "ESAA_CTR",
    "ESGG*_APP",
    "ESMM*_CTR",
    "ESMS*_APP",
    "SCO*E*CTR",
    "SCO*H*CTR",
    "SCO*L*CTR",
    "SCO*N*CTR",
    "SCO_CTR",
]
exclude = [
    "ESMM*6*CTR",
    "ESMM*Y*CTR",
    "EDUU*CHI*CTR",
    "EDWW*EMS*CTR",
]
priority = [
    "DK_FMP",
    "*_FMP",
    "APP CO",
    "DK*",
    "WW*",
    "YY*",
    "UU*",
    "MM*",
    "OS*",
    "NO*",
    "SV*",
    "SCO*",
    "DH*",
    "GG*",
    "APP*",
    "DEP*",
    "CH*",
    "BI*",
    "YT*",
    "AH*",
    "KA*",
    "SP*",
    "RN*",
    "VJ*",
    "SB*",
    "OD*",
    "EB*",
]
frequencies = "ShowAll"
grouping = "None"

[stations.profiles.1_ACC.aliases]
"124.705" = "SV N"
"124.555" = "DK L"
"126.785" = "UU OSE2"
"133.035" = "UU OSE"
"129.840" = "YY BB"
"119.555" = "DK B"
"134.680" = "DK N"
"124.405" = "MM 4"
"120.205" = "FIN"
"121.405" = "VJ AFIS"
"126.825" = "SAA"
"119.530" = "OD AFIS"
"134.980" = "MM L"
"121.550" = "NOS"
"136.555" = "DK UN"
"119.255" = "BI FIN"
"128.215" = "DK C"
"131.040" = "DK FMP"
"121.905" = "CH B GND"
"125.855" = "WW HEI"
"135.565" = "DK V"
"125.500" = "NOR"
"126.400" = "SB AFIS"
"119.580" = "KA TWR"
"119.805" = "APP W"
"132.780" = "YY HOL H"
"128.180" = "MM 8"
"118.580" = "CH C TWR"
"131.280" = "MM K"
"136.280" = "SV W"
"126.325" = "WW ALR"
"132.765" = "MM 5"
"128.055" = "MM 3"
"126.055" = "DK UV"
"124.680" = "GG APP E"
"124.980" = "DEP K"
"123.980" = "YT APP"
"135.985" = "MM 9"
"121.630" = "CH A APN"
"136.485" = "DK UA"
"127.255" = "OS 5"
"127.755" = "MM 2"
"119.280" = "AH APP"
"134.515" = "NOC"
"123.225" = "WW BOR"
"120.540" = "DH APP"
"124.205" = "GG APP W"
"118.530" = "AH TWR"
"128.235" = "UU HVL"
"130.655" = "APP CO"
"120.705" = "YT FIN"
"118.880" = "OS 4"
"124.075" = "WW EID"
"120.860" = "YY HOL L"
"133.260" = "MM W"
"119.355" = "CH D TWR"
"134.355" = "OS 8"
"124.105" = "SP APP"
"124.155" = "MM 7"
"127.675" = "WW WEST"
"120.255" = "DEP R"
"120.155" = "EB AFIS"
"118.105" = "CH A TWR"
"127.580" = "BI APP"
"123.730" = "DK E"
"120.655" = "SV 9"
"118.280" = "SP TWR"
"119.905" = "CH DEL"
"118.905" = "RK TWR"
"118.330" = "RN TWR"
"124.175" = "WW MRZ"
"118.455" = "APP O"
"121.380" = "DK I"
"136.050" = "WW MAR"
"134.205" = "SV O"
"133.725" = "WW ALL"
"119.055" = "BI TWR"
"133.155" = "DK D"
"129.735" = "YY JEV H"
"125.530" = "RK APP"
"127.865" = "DK UC"
"120.430" = "KA APP"
"121.730" = "CH C APN"
"136.465" = "YY JEV L"
"135.290" = "DK A"
"118.305" = "YT TWR"

[stations.profiles.3_EKCH_GND]
include = [
    "EKCH*",
    "EKDK*",
    "*_FMP",
]
exclude = []
priority = [
    "DK FMP",
    "*_FMP",
    "APP CO",
    "DK*",
    "APP*",
    "DEP*",
    "CH*_TWR",
    "CH*_GND",
    "CH*_DEL",
]
frequencies = "ShowAll"
grouping = "None"

[stations.profiles.3_EKCH_GND.aliases]
"128.215" = "DK C"
"126.055" = "DK UV"
"121.905" = "CH B APN"
"118.105" = "CH A TWR"
"119.805" = "APP W"
"123.730" = "DK E"
"119.555" = "DK B"
"136.555" = "DK UN"
"118.580" = "CH C TWR"
"120.205" = "FIN"
"125.530" = "RK APP"
"131.040" = "DK FMP"
"130.655" = "APP CO"
"133.155" = "DK D"
"121.380" = "DK I"
"135.290" = "DK A"
"120.255" = "DEP R"
"124.980" = "DEP K"
"134.680" = "DK N"
"118.455" = "APP O"
"136.485" = "DK UA"
"135.565" = "DK V"
"127.865" = "DK UC"
"119.355" = "CH D TWR"
"121.630" = "CH A APN"
"119.905" = "CH DEL"
"124.555" = "DK L"

[stations.profiles.Default]
include = []
exclude = []
priority = [
    "*_FMP",
    "*_CTR",
    "*_APP",
    "*_TWR",
    "*_GND",
]
frequencies = "ShowAll"
grouping = "None"

[stations.profiles.Default.aliases]

[stations.profiles.2_APP]
include = [
    "EKDK*",
    "EKCH*",
    "EKRK*",
    "ESMS*_APP",
    "ESMM*_CTR",
    "ESAA_CTR",
    "*_FMP",
]
exclude = [
    "ESMM*6*CTR",
    "ESMM*Y*CTR",
    "ESMM*3*CTR",
    "ESMM*4*CTR",
    "ESMM*W*CTR",
    "ESMM*9*CTR",
]
priority = [
    "DK FMP",
    "*_FMP",
    "APP CO",
    "DK*",
    "MM*",
    "APP*",
    "DEP*",
    "CH*_TWR",
    "CH*_GND*",
    "CH*_DEL*",
    "RK*",
]
frequencies = "ShowAll"
grouping = "None"

[stations.profiles.2_APP.aliases]
"132.765" = "MM 5"
"118.455" = "APP O"
"120.255" = "DEP R"
"119.905" = "CH DEL"
"120.205" = "FIN"
"119.805" = "APP W"
"134.980" = "MM L"
"126.055" = "DK UV"
"136.555" = "DK UN"
"124.980" = "DEP K"
"121.730" = "CH C APN"
"134.680" = "DK N"
"124.155" = "MM 7"
"119.555" = "DK B"
"130.655" = "APP CO"
"119.355" = "CH D TWR"
"121.630" = "CH A APN"
"136.485" = "DK UA"
"124.405" = "MM 4"
"128.180" = "MM 8"
"131.040" = "DK FMP"
"128.055" = "MM 3"
"121.380" = "DK I"
"135.565" = "DK V"
"121.905" = "CH B APN"
"126.825" = "SAA"
"123.730" = "DK E"
"127.755" = "MM 2"
"124.555" = "DK L"
"131.280" = "MM K"
"128.215" = "DK C"
"118.580" = "CH C TWR"
"127.865" = "DK UC"
"118.105" = "CH A TWR"
"133.155" = "DK D"
"125.530" = "RK APP"
"135.290" = "DK A"
